# Generated by Django 3.0.8 on 2020-07-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200709_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-mod_date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
