# Generated by Django 2.2.14 on 2020-07-19 12:24

from django.db import migrations, models
import genealogy.models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_auto_20200719_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='fost',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='fost',
            name='file',
            field=models.FileField(null=True, upload_to=genealogy.models.get_file_path),
        ),
    ]
