# Generated by Django 2.2.14 on 2020-07-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_auto_20200719_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='fost',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
