# Generated by Django 2.2.14 on 2020-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_fost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fost',
            name='file',
            field=models.FileField(null=True, upload_to='genealogy/files'),
        ),
    ]
