# Generated by Django 2.2.14 on 2020-07-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_auto_20200719_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fost',
            name='file',
            field=models.FileField(null=True, upload_to='get_file_path'),
        ),
    ]
